[scene.hello]
background = "@assets/bg/yard.png"

[[scene.hello.characters]]
ref = "a"
animation = "enterLeft 3s"

[[scene.hello.dialogue]]
speaker = "Aoi Mizuno"
say.text = "Hello, Yuna Tachibana! Welcome to the world of Ren'Py in Go!"
say.effect = "Fade"
goto=">begin"