[scene.begin]
background = "@assets/bg/base.jpg"
background_music = "@assets/audio/bgm/Ghostly Dream - Snow or Cherry Petal.mp3"
zoom = 100

[[scene.begin.characters]]
ref = "k"
animation = "enterLeft 1s"


[[scene.begin.characters]]
name = "Reimu"
sprite = "@assets/characters/reimu.png"
animation = "enterRight"
shown = false


[[scene.begin.dialogue]]
speaker = "Kasen"
say.text = "Hello, Reimu! Welcome to the world of Ren'Py in Go!"
say.effect = "Fade"


[[scene.begin.dialogue]]
speaker = "Kasen"
input.label = "What's your name?"
input.placeholder = "Enter your name"
input.type = "text"
input.validation = "nonempty"
input.on_submit_set = "vars.player.name = Sr. <input>"
save = true


[[scene.begin.dialogue]]
speaker = "Reimu"
say.text = "Hello ${vars.player.name}! It's great to meet you. I'm excited to show you ${vars.world.name} and all the amazing things we can create with it!"
say.effect = "Write"


[[scene.begin.dialogue]]
togo = "test2"
speaker = "Reimu"
say.text = "Hi, Kasen! This is amazing! I can't wait to see what we can do with this engine!"
say.effect = "Write"


[[scene.begin.dialogue]]
togo = "test3"
speaker = "Reimu"
shown = true
say.text = "Let's start by creating a new scene and adding some dialogue!"
say.effect = "Wavy"


[[scene.begin.dialogue]]
speaker = "Kasen"
say.text = "Great idea! We can also add some character animations and background music to make it more immersive!"


[[scene.begin.dialogue]]
togo = "test4"
speaker = "Reimu"
ask.question = "What should we do first?"
ask.options = [
    "Create a new scene", #goto test1
    "Add character animations", #goto test2
    {text = "Add background music", goto = "test3"},
    {text = "All of the above"}, #dont have goto
    "Reask the question", #goto test4
]