[scene.begin]
background = "@assets/bg.jpg"
msg = "Hello, World!"

[[scene.begin.characters]]
name = "Kasen"
sprite = "@assets/kasen.png"
animation = "enterLeft 1s"


[[scene.begin.characters]]
name = "Reimu"
sprite = "@assets/reimu.png"
animation = "enterRight 3s"