[scene.begin]
background = "@assets/bg.jpg"
zoom = 100

[[scene.begin.characters]]
name = "Kasen"
sprite = "@assets/kasen.png"
animation = "enterLeft 1s"


[[scene.begin.characters]]
name = "Reimu"
sprite = "@assets/reimu.png"
animation = "enterRight"