[global.info]
title = "TinyRen"
description = "A description of my project."
version = "1.0.0"
author = "John Doe"

[global.settings]
width = 800
height = 600
fullscreen = false

[[global.characters]]
name = "Kasen"
alias = "k"
sprite = "@assets/characters/kasen.png"

[[global.characters]]
name = "Reimu"
alias = "r"
sprite = "@assets/characters/reimu.png"