// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetBackground() {
  return window['go']['main']['App']['GetBackground']();
}

export function GetCharacterAnimationData(arg1) {
  return window['go']['main']['App']['GetCharacterAnimationData'](arg1);
}

export function GetCharacterSprite(arg1) {
  return window['go']['main']['App']['GetCharacterSprite'](arg1);
}

export function GetMenu() {
  return window['go']['main']['App']['GetMenu']();
}

export function GetMenuBackground() {
  return window['go']['main']['App']['GetMenuBackground']();
}

export function GetScene(arg1) {
  return window['go']['main']['App']['GetScene'](arg1);
}

export function GetVars() {
  return window['go']['main']['App']['GetVars']();
}

export function PlayAudio(arg1) {
  return window['go']['main']['App']['PlayAudio'](arg1);
}

export function Save() {
  return window['go']['main']['App']['Save']();
}

export function SetVar(arg1, arg2) {
  return window['go']['main']['App']['SetVar'](arg1, arg2);
}

export function ShowExitMessage() {
  return window['go']['main']['App']['ShowExitMessage']();
}
