// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {toml} from '../models';

export function Close():Promise<void>;

export function GetBackground():Promise<string>;

export function GetCharacterAnimationData(arg1:string):Promise<toml.CharacterAnimationData>;

export function GetCharacterSprite(arg1:toml.Character):Promise<string>;

export function GetMenu():Promise<toml.Menu>;

export function GetMenuBackground():Promise<string>;

export function GetScene(arg1:string):Promise<toml.Scene>;

export function GetVars():Promise<Record<string, any>>;

export function PlayAudio(arg1:string):Promise<void>;

export function Save():Promise<Record<string, any>>;

export function SetVar(arg1:string,arg2:any):Promise<void>;

export function ShowExitMessage():Promise<boolean>;
