// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {toml} from '../models';

export function GetBackground():Promise<string>;

export function GetScene(arg1:string):Promise<toml.Scene>;

export function Greet(arg1:string):Promise<string>;
