// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackground() {
  return window['go']['main']['App']['GetBackground']();
}

export function GetCharacterAnimationData(arg1) {
  return window['go']['main']['App']['GetCharacterAnimationData'](arg1);
}

export function GetCharacterSprite(arg1) {
  return window['go']['main']['App']['GetCharacterSprite'](arg1);
}

export function GetScene(arg1) {
  return window['go']['main']['App']['GetScene'](arg1);
}

export function PlayAudio(arg1) {
  return window['go']['main']['App']['PlayAudio'](arg1);
}
